# Generated by Django 2.2 on 2020-02-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0005_auto_20200202_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='receive_currency',
            new_name='pay_currency',
        ),
    ]
