# Generated by Django 2.2 on 2020-02-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0006_auto_20200202_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pay_amount',
            new_name='receive_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pay_currency',
        ),
        migrations.AddField(
            model_name='order',
            name='receive_currency',
            field=models.CharField(blank=True, choices=[('EUR', 'EUR'), ('USD', 'USD'), ('CAD', 'CAD'), ('BTC', 'BTC'), ('ETH', 'ETH')], max_length=8, null=True),
        ),
    ]
