# Generated by Django 2.2 on 2020-02-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_amount', models.PositiveIntegerField()),
                ('price_curenncy', models.CharField(choices=[('BTC', 'Bitcoin'), ('BTC_LC', 'Litecoin'), ('BTC_BC', 'Bitcoin Cash'), ('BTC_EC', 'Etgereum Classic')], max_length=8)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
