# Generated by Django 2.2 on 2020-02-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0007_auto_20200202_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='receive_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
