# Generated by Django 2.2 on 2020-02-02 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0008_auto_20200202_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price_curenncy',
            new_name='price_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receive_amount',
        ),
    ]
